version: 0.0
os: linux
files:
  - source: target/pcf-demo.war
    destination: /var/lib/tomcat8/webapps/
hooks:
  ApplicationStop:
    - location: ci/scripts/tomcat_stop.sh
      runas: root
  ApplicationStart:
    - location: ci/scripts/tomcat_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: ci/scripts/verify_service.sh
      timeout: 300
      runas: root
